config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :paths => 'users'

  
    
  resources :users do
    resources :playlists, :places 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :themes do  
    resources :categories
  end

  resources :categories do
    resources  :playlists, :places
  end

  resources :playlists, :places do
    resources :links
  end

  root "themes#index"
end

app/models/playlist.rb
# == Schema Information
#
# Table name: playlists
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  category_id :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  theme_id    :integer
#

class Playlist < ApplicationRecord
  belongs_to :category
  belongs_to :user , optional: true
  has_many :links, as: :linkable
  accepts_nested_attributes_for :links, allow_destroy: true

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
    before_action :set_playlist, only: [:show, :edit, :update, :destroy]

    def index 
        @playlists = Playlist.all
    end 

    def new
        @playlist = Playlist.new
    end

    def create 
        @playlist = Playlist.create(playlist_params)
        if @playlist.save
             flash[:success] = "Your new playlist has been created !"
        redirect_to @playlist
        else 
             flash.now[:alert] = "Your new playlist couldn't be created!  Please check the form."
            render 'new'
        end
    end

    def show
        set_playlist
    end

    def edit 
        set_playlist
    end 

    def update
        set_playlist
        if
            @playlist.update(playlist_params)
            flash[:success] = "Votre playlist a bien été modifié !"
        redirect_to(playlist_path(@playlist))
        else 
            flash.now[:alert] = "Nous avons rencontré un problème. Veuillez vérifier le formulaire"
            render 
        end
    end

    
    def destroy
        set_playlist
        @playlist.destroy
        redirect_to playlists_path
    end



    private 

    def playlist_params
        params.require(:playlist).permit(:description, :name,:category_id,:theme_id)
    end


    def set_playlist
        @playlist = Playlist.find(params[:id])
    end

end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_playlists.html.erb
<%= playlists.name %> <br>
<%= playlists.description %> <br> 
<%= link_to  "New playlist", new_playlist_path %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= form_for @playlist do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :theme_id %><br />
    <%= f.collection_select :theme_id, Theme.order(:name), :id, :name, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :category_id, "State or Province" %><br />
    <%= f.grouped_collection_select :category_id, Theme.order(:name), :categories, :name, :id, :name, include_blank: true %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>