config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :paths => 'users'

  
    
  resources :users do
    resources :playlists, :places 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :themes do  
    resources :categories
  end

  resources :categories do
    resources  :playlists, :places
  end

  resources :playlists, :places do
    resources :links
  end

  root "themes#index"
end

app/models/place.rb
# == Schema Information
#
# Table name: places
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  category_id :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  theme_id    :integer
#

class Place < ApplicationRecord
  belongs_to :category
  belongs_to :user , optional: true
  has_many :links, as: :linkable
  accepts_nested_attributes_for :links, allow_destroy: true
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
    before_action :set_place, only: [:show, :edit, :update, :destroy]

    def index 
        @places = Place.all
    end 

    def new
        @place = Place.new
    end

    def create 
        @place = Place.create(place_params)
        if @place.save
             flash[:success] = "Your new place has been created !"
        redirect_to @place
        else 
             flash.now[:alert] = "Your new place couldn't be created!  Please check the form."
            render 'new'
        end
    end

    def show
        set_place
    end

    def edit 
        set_place
    end 

    def update
        set_place
        if
            @place.update(place_params)
            flash[:success] = "Votre place a bien été modifié !"
        redirect_to(place_path(@place))
        else 
            flash.now[:alert] = "Nous avons rencontré un problème. Veuillez vérifier le formulaire"
            render 
        end
    end

    
    def destroy
        set_place
        @place.destroy
        redirect_to places_path
    end



    private 

    def place_params
        params.require(:place).permit(:description, :name, :theme_id, :category_id)
    end


    def set_place
        @place = Place.find(params[:id])
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_places.html.erb
<%= places.name %>
<%= places.description %>
<%= link_to  "New Place", new_place_path(@theme) %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= form_for @place do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :theme_id %><br />
    <%= f.collection_select :theme_id, Theme.order(:name), :id, :name, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :category_id, "State or Province" %><br />
    <%= f.grouped_collection_select :category_id, Theme.order(:name), :categories, :name, :id, :name, include_blank: true %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>